import 'package:tmdbmaze/src/feature/movies/domain/entities/filter_options.dart';

/// Predefined comprehensive filter options that include all possible values
class PredefinedFilterOptions {
  // Common show types from TVMaze API
  static const List<String> allTypes = [
    'Documentary',
    'Drama',
    'Animation',
    'Action',
    'Adventure',
    'Children',
    'Comedy',
    'Crime',
    'Family',
    'Fantasy',
    'Food',
    'Game Show',
    'History',
    'Horror',
    'Legal',
    'Medical',
    'Music',
    'Mystery',
    'Nature',
    'News',
    'Reality',
    'Romance',
    'Science-Fiction',
    'Sports',
    'Talk Show',
    'Thriller',
    'War',
    'Western',
  ];

  // Common show statuses from TVMaze API
  static const List<String> allStatuses = ['Running', 'Ended', 'To Be Determined'];

  // Countries that actively produce TV content
  static const Map<String, String> allCountries = {
    'US': 'United States',
    'GB': 'United Kingdom',
    'CA': 'Canada',
    'AU': 'Australia',
    'NZ': 'New Zealand',
    'IE': 'Ireland',
    'DE': 'Germany',
    'FR': 'France',
    'IT': 'Italy',
    'ES': 'Spain',
    'NL': 'Netherlands',
    'BE': 'Belgium',
    'SE': 'Sweden',
    'NO': 'Norway',
    'DK': 'Denmark',
    'FI': 'Finland',
    'PL': 'Poland',
    'CZ': 'Czech Republic',
    'RU': 'Russia',
    'UA': 'Ukraine',
    'PT': 'Portugal',
    'GR': 'Greece',
    'TR': 'Turkey',
    'JP': 'Japan',
    'KR': 'South Korea',
    'CN': 'China',
    'IN': 'India',
    'BR': 'Brazil',
    'MX': 'Mexico',
    'AR': 'Argentina',
    'CL': 'Chile',
    'CO': 'Colombia',
    'PE': 'Peru',
    'ZA': 'South Africa',
    'IL': 'Israel',
    'SG': 'Singapore',
    'MY': 'Malaysia',
    'TH': 'Thailand',
    'ID': 'Indonesia',
    'PH': 'Philippines',
    'VN': 'Vietnam',
    'HK': 'Hong Kong',
    'TW': 'Taiwan',
    'AT': 'Austria',
    'CH': 'Switzerland',
    'HU': 'Hungary',
    'RO': 'Romania',
    'SK': 'Slovakia',
    'IS': 'Iceland',
    'UY': 'Uruguay',
    'CR': 'Costa Rica',
    'PR': 'Puerto Rico',
    'CU': 'Cuba',
    'DO': 'Dominican Republic',
    'JM': 'Jamaica',
    'PA': 'Panama',
    'VE': 'Venezuela',
    'EC': 'Ecuador',
    'PK': 'Pakistan',
    'BD': 'Bangladesh',
    'AE': 'United Arab Emirates',
    'SA': 'Saudi Arabia',
    'EG': 'Egypt',
    'KE': 'Kenya',
    'NG': 'Nigeria',
    'GH': 'Ghana',
    'MG': 'Madagascar',
    'MU': 'Mauritius',
    'LK': 'Sri Lanka',
    'MM': 'Myanmar',
    'BN': 'Brunei',
    'KZ': 'Kazakhstan',
  };

  /// Get a comprehensive FilterOptions object with all predefined options
  /// Note: types array is now empty as we filter by genres instead
  static FilterOptions getComprehensiveOptions() => const FilterOptions(
    types: [],
    statuses: allStatuses,
    genres: _allGenres,
    countries: allCountries,
  );

  /// Common genres that may appear in shows
  static const List<String> _allGenres = [
    'Action',
    'Adventure',
    'Anime',
    'Animation',
    'Award Show',
    'Children',
    'Comedy',
    'Contest',
    'Crime',
    'Current Affairs',
    'Dance',
    'Documentary',
    'Drama',
    'Dramedy',
    'Erotic',
    'Espionage',
    'Event',
    'Family',
    'Fantasy',
    'Food',
    'Game Show',
    'Game-Show',
    'Golf',
    'Guessing Game',
    'History',
    'Horror',
    'Improv',
    'Japanese',
    'Legal',
    'Life',
    'Medical',
    'Magic',
    'Martial Arts',
    'Melodrama',
    'Military',
    'Mini-Series',
    'Music',
    'Musical',
    'Mystery',
    'Nature',
    'News',
    'Panel Show',
    'Period',
    'Podcast',
    'Political',
    'Quiz',
    'Reality',
    'Reality-TV',
    'Psychological',
    'Romance',
    'Romantic Comedy',
    'Sci-Fi',
    'Science-Fiction',
    'Sketch',
    'Sports',
    'Sports Event',
    'Standup',
    'Survival',
    'Suspense',
    'Talk Show',
    'Thriller',
    'Travel',
    'Video',
    'Variety',
    'War',
    'Weather',
    'Western',
  ];
}
